/*
 * Tencent is pleased to support the open source community by making TKEStack
 * available.
 *
 * Copyright (C) 2012-2020 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use
 * this file except in compliance with the License. You may obtain a copy of the
 * License at
 *
 * https://opensource.org/licenses/Apache-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OF ANY KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations under the License.
 */

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	authzv1 "tkestack.io/tke/api/authz/v1"
)

// FakeClusterPolicyBindings implements ClusterPolicyBindingInterface
type FakeClusterPolicyBindings struct {
	Fake *FakeAuthzV1
	ns   string
}

var clusterpolicybindingsResource = schema.GroupVersionResource{Group: "authz.tkestack.io", Version: "v1", Resource: "clusterpolicybindings"}

var clusterpolicybindingsKind = schema.GroupVersionKind{Group: "authz.tkestack.io", Version: "v1", Kind: "ClusterPolicyBinding"}

// Get takes name of the clusterPolicyBinding, and returns the corresponding clusterPolicyBinding object, and an error if there is any.
func (c *FakeClusterPolicyBindings) Get(ctx context.Context, name string, options v1.GetOptions) (result *authzv1.ClusterPolicyBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(clusterpolicybindingsResource, c.ns, name), &authzv1.ClusterPolicyBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*authzv1.ClusterPolicyBinding), err
}

// List takes label and field selectors, and returns the list of ClusterPolicyBindings that match those selectors.
func (c *FakeClusterPolicyBindings) List(ctx context.Context, opts v1.ListOptions) (result *authzv1.ClusterPolicyBindingList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(clusterpolicybindingsResource, clusterpolicybindingsKind, c.ns, opts), &authzv1.ClusterPolicyBindingList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &authzv1.ClusterPolicyBindingList{ListMeta: obj.(*authzv1.ClusterPolicyBindingList).ListMeta}
	for _, item := range obj.(*authzv1.ClusterPolicyBindingList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested clusterPolicyBindings.
func (c *FakeClusterPolicyBindings) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(clusterpolicybindingsResource, c.ns, opts))

}

// Create takes the representation of a clusterPolicyBinding and creates it.  Returns the server's representation of the clusterPolicyBinding, and an error, if there is any.
func (c *FakeClusterPolicyBindings) Create(ctx context.Context, clusterPolicyBinding *authzv1.ClusterPolicyBinding, opts v1.CreateOptions) (result *authzv1.ClusterPolicyBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(clusterpolicybindingsResource, c.ns, clusterPolicyBinding), &authzv1.ClusterPolicyBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*authzv1.ClusterPolicyBinding), err
}

// Update takes the representation of a clusterPolicyBinding and updates it. Returns the server's representation of the clusterPolicyBinding, and an error, if there is any.
func (c *FakeClusterPolicyBindings) Update(ctx context.Context, clusterPolicyBinding *authzv1.ClusterPolicyBinding, opts v1.UpdateOptions) (result *authzv1.ClusterPolicyBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(clusterpolicybindingsResource, c.ns, clusterPolicyBinding), &authzv1.ClusterPolicyBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*authzv1.ClusterPolicyBinding), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeClusterPolicyBindings) UpdateStatus(ctx context.Context, clusterPolicyBinding *authzv1.ClusterPolicyBinding, opts v1.UpdateOptions) (*authzv1.ClusterPolicyBinding, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(clusterpolicybindingsResource, "status", c.ns, clusterPolicyBinding), &authzv1.ClusterPolicyBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*authzv1.ClusterPolicyBinding), err
}

// Delete takes name of the clusterPolicyBinding and deletes it. Returns an error if one occurs.
func (c *FakeClusterPolicyBindings) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(clusterpolicybindingsResource, c.ns, name), &authzv1.ClusterPolicyBinding{})

	return err
}

// Patch applies the patch and returns the patched clusterPolicyBinding.
func (c *FakeClusterPolicyBindings) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *authzv1.ClusterPolicyBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(clusterpolicybindingsResource, c.ns, name, pt, data, subresources...), &authzv1.ClusterPolicyBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*authzv1.ClusterPolicyBinding), err
}
