/*
 * Tencent is pleased to support the open source community by making TKEStack
 * available.
 *
 * Copyright (C) 2012-2020 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use
 * this file except in compliance with the License. You may obtain a copy of the
 * License at
 *
 * https://opensource.org/licenses/Apache-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OF ANY KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations under the License.
 */

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	authz "tkestack.io/tke/api/authz"
)

// FakeClusterRoleTemplateBindings implements ClusterRoleTemplateBindingInterface
type FakeClusterRoleTemplateBindings struct {
	Fake *FakeAuthz
	ns   string
}

var clusterroletemplatebindingsResource = schema.GroupVersionResource{Group: "authz.tkestack.io", Version: "", Resource: "clusterroletemplatebindings"}

var clusterroletemplatebindingsKind = schema.GroupVersionKind{Group: "authz.tkestack.io", Version: "", Kind: "ClusterRoleTemplateBinding"}

// Get takes name of the clusterRoleTemplateBinding, and returns the corresponding clusterRoleTemplateBinding object, and an error if there is any.
func (c *FakeClusterRoleTemplateBindings) Get(ctx context.Context, name string, options v1.GetOptions) (result *authz.ClusterRoleTemplateBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(clusterroletemplatebindingsResource, c.ns, name), &authz.ClusterRoleTemplateBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*authz.ClusterRoleTemplateBinding), err
}

// List takes label and field selectors, and returns the list of ClusterRoleTemplateBindings that match those selectors.
func (c *FakeClusterRoleTemplateBindings) List(ctx context.Context, opts v1.ListOptions) (result *authz.ClusterRoleTemplateBindingList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(clusterroletemplatebindingsResource, clusterroletemplatebindingsKind, c.ns, opts), &authz.ClusterRoleTemplateBindingList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &authz.ClusterRoleTemplateBindingList{ListMeta: obj.(*authz.ClusterRoleTemplateBindingList).ListMeta}
	for _, item := range obj.(*authz.ClusterRoleTemplateBindingList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested clusterRoleTemplateBindings.
func (c *FakeClusterRoleTemplateBindings) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(clusterroletemplatebindingsResource, c.ns, opts))

}

// Create takes the representation of a clusterRoleTemplateBinding and creates it.  Returns the server's representation of the clusterRoleTemplateBinding, and an error, if there is any.
func (c *FakeClusterRoleTemplateBindings) Create(ctx context.Context, clusterRoleTemplateBinding *authz.ClusterRoleTemplateBinding, opts v1.CreateOptions) (result *authz.ClusterRoleTemplateBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(clusterroletemplatebindingsResource, c.ns, clusterRoleTemplateBinding), &authz.ClusterRoleTemplateBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*authz.ClusterRoleTemplateBinding), err
}

// Update takes the representation of a clusterRoleTemplateBinding and updates it. Returns the server's representation of the clusterRoleTemplateBinding, and an error, if there is any.
func (c *FakeClusterRoleTemplateBindings) Update(ctx context.Context, clusterRoleTemplateBinding *authz.ClusterRoleTemplateBinding, opts v1.UpdateOptions) (result *authz.ClusterRoleTemplateBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(clusterroletemplatebindingsResource, c.ns, clusterRoleTemplateBinding), &authz.ClusterRoleTemplateBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*authz.ClusterRoleTemplateBinding), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeClusterRoleTemplateBindings) UpdateStatus(ctx context.Context, clusterRoleTemplateBinding *authz.ClusterRoleTemplateBinding, opts v1.UpdateOptions) (*authz.ClusterRoleTemplateBinding, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(clusterroletemplatebindingsResource, "status", c.ns, clusterRoleTemplateBinding), &authz.ClusterRoleTemplateBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*authz.ClusterRoleTemplateBinding), err
}

// Delete takes name of the clusterRoleTemplateBinding and deletes it. Returns an error if one occurs.
func (c *FakeClusterRoleTemplateBindings) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(clusterroletemplatebindingsResource, c.ns, name), &authz.ClusterRoleTemplateBinding{})

	return err
}

// Patch applies the patch and returns the patched clusterRoleTemplateBinding.
func (c *FakeClusterRoleTemplateBindings) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *authz.ClusterRoleTemplateBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(clusterroletemplatebindingsResource, c.ns, name, pt, data, subresources...), &authz.ClusterRoleTemplateBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*authz.ClusterRoleTemplateBinding), err
}
