/*
 * Tencent is pleased to support the open source community by making TKEStack
 * available.
 *
 * Copyright (C) 2012-2020 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use
 * this file except in compliance with the License. You may obtain a copy of the
 * License at
 *
 * https://opensource.org/licenses/Apache-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OF ANY KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations under the License.
 */

// Code generated by client-gen. DO NOT EDIT.

package internalversion

import (
	"context"
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	authz "tkestack.io/tke/api/authz"
	scheme "tkestack.io/tke/api/client/clientset/internalversion/scheme"
)

// RoleTemplatesGetter has a method to return a RoleTemplateInterface.
// A group's client should implement this interface.
type RoleTemplatesGetter interface {
	RoleTemplates(namespace string) RoleTemplateInterface
}

// RoleTemplateInterface has methods to work with RoleTemplate resources.
type RoleTemplateInterface interface {
	Create(ctx context.Context, roleTemplate *authz.RoleTemplate, opts v1.CreateOptions) (*authz.RoleTemplate, error)
	Update(ctx context.Context, roleTemplate *authz.RoleTemplate, opts v1.UpdateOptions) (*authz.RoleTemplate, error)
	UpdateStatus(ctx context.Context, roleTemplate *authz.RoleTemplate, opts v1.UpdateOptions) (*authz.RoleTemplate, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*authz.RoleTemplate, error)
	List(ctx context.Context, opts v1.ListOptions) (*authz.RoleTemplateList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *authz.RoleTemplate, err error)
	RoleTemplateExpansion
}

// roleTemplates implements RoleTemplateInterface
type roleTemplates struct {
	client rest.Interface
	ns     string
}

// newRoleTemplates returns a RoleTemplates
func newRoleTemplates(c *AuthzClient, namespace string) *roleTemplates {
	return &roleTemplates{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the roleTemplate, and returns the corresponding roleTemplate object, and an error if there is any.
func (c *roleTemplates) Get(ctx context.Context, name string, options v1.GetOptions) (result *authz.RoleTemplate, err error) {
	result = &authz.RoleTemplate{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("roletemplates").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of RoleTemplates that match those selectors.
func (c *roleTemplates) List(ctx context.Context, opts v1.ListOptions) (result *authz.RoleTemplateList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &authz.RoleTemplateList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("roletemplates").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested roleTemplates.
func (c *roleTemplates) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("roletemplates").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a roleTemplate and creates it.  Returns the server's representation of the roleTemplate, and an error, if there is any.
func (c *roleTemplates) Create(ctx context.Context, roleTemplate *authz.RoleTemplate, opts v1.CreateOptions) (result *authz.RoleTemplate, err error) {
	result = &authz.RoleTemplate{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("roletemplates").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(roleTemplate).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a roleTemplate and updates it. Returns the server's representation of the roleTemplate, and an error, if there is any.
func (c *roleTemplates) Update(ctx context.Context, roleTemplate *authz.RoleTemplate, opts v1.UpdateOptions) (result *authz.RoleTemplate, err error) {
	result = &authz.RoleTemplate{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("roletemplates").
		Name(roleTemplate.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(roleTemplate).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *roleTemplates) UpdateStatus(ctx context.Context, roleTemplate *authz.RoleTemplate, opts v1.UpdateOptions) (result *authz.RoleTemplate, err error) {
	result = &authz.RoleTemplate{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("roletemplates").
		Name(roleTemplate.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(roleTemplate).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the roleTemplate and deletes it. Returns an error if one occurs.
func (c *roleTemplates) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("roletemplates").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched roleTemplate.
func (c *roleTemplates) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *authz.RoleTemplate, err error) {
	result = &authz.RoleTemplate{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("roletemplates").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
