/*
 * Tencent is pleased to support the open source community by making TKEStack
 * available.
 *
 * Copyright (C) 2012-2020 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use
 * this file except in compliance with the License. You may obtain a copy of the
 * License at
 *
 * https://opensource.org/licenses/Apache-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OF ANY KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations under the License.
 */

// Code generated by lister-gen. DO NOT EDIT.

package internalversion

import (
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
	authz "tkestack.io/tke/api/authz"
)

// RoleTemplateLister helps list RoleTemplates.
// All objects returned here must be treated as read-only.
type RoleTemplateLister interface {
	// List lists all RoleTemplates in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*authz.RoleTemplate, err error)
	// RoleTemplates returns an object that can list and get RoleTemplates.
	RoleTemplates(namespace string) RoleTemplateNamespaceLister
	RoleTemplateListerExpansion
}

// roleTemplateLister implements the RoleTemplateLister interface.
type roleTemplateLister struct {
	indexer cache.Indexer
}

// NewRoleTemplateLister returns a new RoleTemplateLister.
func NewRoleTemplateLister(indexer cache.Indexer) RoleTemplateLister {
	return &roleTemplateLister{indexer: indexer}
}

// List lists all RoleTemplates in the indexer.
func (s *roleTemplateLister) List(selector labels.Selector) (ret []*authz.RoleTemplate, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*authz.RoleTemplate))
	})
	return ret, err
}

// RoleTemplates returns an object that can list and get RoleTemplates.
func (s *roleTemplateLister) RoleTemplates(namespace string) RoleTemplateNamespaceLister {
	return roleTemplateNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// RoleTemplateNamespaceLister helps list and get RoleTemplates.
// All objects returned here must be treated as read-only.
type RoleTemplateNamespaceLister interface {
	// List lists all RoleTemplates in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*authz.RoleTemplate, err error)
	// Get retrieves the RoleTemplate from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*authz.RoleTemplate, error)
	RoleTemplateNamespaceListerExpansion
}

// roleTemplateNamespaceLister implements the RoleTemplateNamespaceLister
// interface.
type roleTemplateNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all RoleTemplates in the indexer for a given namespace.
func (s roleTemplateNamespaceLister) List(selector labels.Selector) (ret []*authz.RoleTemplate, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*authz.RoleTemplate))
	})
	return ret, err
}

// Get retrieves the RoleTemplate from the indexer for a given namespace and name.
func (s roleTemplateNamespaceLister) Get(name string) (*authz.RoleTemplate, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(authz.Resource("roletemplate"), name)
	}
	return obj.(*authz.RoleTemplate), nil
}
